### Create a Basic feedforward neural network for binary classification 
* (use generate input using NumPy random module)

#### Step 1: Import the required libraries

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#### Step 2: Generate random data

In [2]:
np.random.seed(1234)

# 1000 samples, 10 features
X = np.random.rand(1000, 10)

# Binary target variable
y = (np.sum(X, axis=1) > 5).astype(int)

In [3]:
X[:3]

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
        0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263],
       [0.35781727, 0.50099513, 0.68346294, 0.71270203, 0.37025075,
        0.56119619, 0.50308317, 0.01376845, 0.77282662, 0.88264119],
       [0.36488598, 0.61539618, 0.07538124, 0.36882401, 0.9331401 ,
        0.65137814, 0.39720258, 0.78873014, 0.31683612, 0.56809865]])

In [4]:
y[:100]

array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [5]:
unique_values, counts = np.unique(y, return_counts=True)
print(unique_values, counts)

[0 1] [495 505]


#### Step3:  Split the data into train and test sets

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1234)

In [7]:
for ds in [X_train, X_test, y_train, y_test]:
    print(ds.shape)

(750, 10)
(250, 10)
(750,)
(250,)


#### Step 4: Standardize the data

In [8]:
scaler = StandardScaler()

In [9]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train[:3]

array([[-0.31001174, -1.53011143, -0.43589841, -0.36741297,  1.36274025,
        -0.3691732 ,  0.09209503,  0.39047185, -0.03587956,  0.18586554],
       [-0.46891276,  0.21535725, -0.61573424,  1.52658122, -1.50188944,
        -0.83122368, -0.19136724, -1.17625983, -1.02639508, -0.72651318],
       [-0.04174127,  1.46763399,  0.22509391, -0.62813791, -0.4655329 ,
        -1.49386288,  1.66644136, -0.43615968,  1.05656838,  0.04505254]])

In [11]:
X_test[:3]

array([[-1.02038091, -0.79628135,  0.09630399, -0.78386751, -1.23380455,
         1.49330077, -0.34594412,  1.43593942, -0.83075568,  0.10316581],
       [-0.27269567, -1.42747127,  1.17626614, -1.43113541, -0.27900412,
        -0.36675459,  0.27380467,  0.00799122,  0.02508702, -1.35772616],
       [-0.02873211, -0.55145641, -1.06679608, -1.14081759,  0.24545523,
        -0.14840791,  1.23435655,  1.42792525,  1.20839151,  1.63879321]])

#### Step 5: Defining the Feed-Forward Neural Network Model 

In [12]:
model = Sequential([
    Dense(8, input_dim=10, activation='relu'),  # Input layer with 10 features and 8 neurons
    Dense(4, activation='relu'),  # Hidden layer with 4 neurons
    Dense(1, activation='sigmoid')  # Output layer with 1 neuron only and sigmoid activation
])

C:\Users\saura\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


#### Step 6: Compile the model

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#### Step 7: Traning the Model

In [14]:
ff_model = model.fit(X_train, y_train, epochs=20, batch_size=50)

Epoch 1/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.5384 - loss: 0.6829
Epoch 2/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5541 - loss: 0.6626 
Epoch 3/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5953 - loss: 0.6325 
Epoch 4/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.5917 
Epoch 5/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7004 - loss: 0.5839 
Epoch 6/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7478 - loss: 0.5679 
Epoch 7/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7506 - loss: 0.5455
Epoch 8/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7493 - loss: 0.5357 
Epoch 9/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8336 - loss: 0.4970 
Epoch 10/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8126 - loss: 0.4861 
Epoch 11/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8567 - loss: 0.4477
Epoch 12/20
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8

#### Step8: Evaluation of the model on the test-set

In [15]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy*100:.2f}%')

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9094 - loss: 0.2635  
Test Loss: 0.2810
Test Accuracy: 90.00%


In [16]:
# Predict on test data
y_pred = model.predict(X_test)
y_pred[:5]

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


array([[0.29780233],
       [0.18328127],
       [0.85134465],
       [0.44431785],
       [0.15533708]], dtype=float32)

In [17]:
# Conversion of probabilities to binary classes
y_pred_classes = (y_pred > 0.5).astype(int)

In [18]:
# Display first 100 predictions
print("First 100 Predictions:", "\n", y_pred_classes[:100].flatten())

First 100 Predictions: 
 [0 0 1 0 0 0 1 1 0 0 1 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1 0
 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1
 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1]
