### Use Keras library to create and train a basic RNN for sequence prediction.
* Use a simple sequence (8 ,9, 10, 11, 12, 13)

#### Step 1: Import the required libraries

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

#### Step 2: Create the sequence

In [2]:
sq = np.array([8, 9, 10, 11, 12, 13])

#### Step 3: input and output pairs

In [3]:
X = sq[:-1]
y = sq[1:]

In [4]:
X

array([ 8,  9, 10, 11, 12])

In [5]:
y

array([ 9, 10, 11, 12, 13])

#### Step 4: Reshape the data to fit the RNN input requirements

In [6]:
#batch_size, sequence_length, num_features
X = X.reshape((1, X.shape[0], 1))  
y = y.reshape((1, y.shape[0], 1))

In [7]:
X

array([[[ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [8]:
y

array([[[ 9],
        [10],
        [11],
        [12],
        [13]]])

#### Step 5: Define the RNN model

In [9]:
model = Sequential([SimpleRNN(50, activation='relu'), Dense(1)])

#### Step 6: Compile the model

In [10]:
model.compile(optimizer='adam', loss='mse')

#### Step 7: Train the model

In [11]:
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 182.7769
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 175.7035
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 168.8185
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 162.0583
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 155.4279
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 148.9230
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 142.5405
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 136.2765
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 130.2209
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 124.3043
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 118.4862
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 112.8389
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 107.9084
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 103.2028
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss

#### Step 8: Make prediction

In [12]:
new_input = np.array([9, 10, 11, 12, 13]).reshape((1, 5, 1))
new_input

array([[[ 9],
        [10],
        [11],
        [12],
        [13]]])

In [13]:
predicted = model.predict(new_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step


In [14]:
predicted

array([[12.055693]], dtype=float32)

In [15]:
print(f'Predicted next value: {predicted[-1][0]}')

Predicted next value: 12.055692672729492
