### Create a Basic Recurrent Nerural Network (RNN) model for text analysis using Python and Tensorflow.
* (Input text = "Anna, embrace change; Change is constant."

#### Step 1: Import the required libraries

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

#### Step 2: Input text

In [2]:
text = "Anna, embrace change; Change is constant."

#### Step 3: Create a list of letters

In [3]:
char_list = sorted(set(text))
print(char_list)

[' ', ',', '.', ';', 'A', 'C', 'a', 'b', 'c', 'e', 'g', 'h', 'i', 'm', 'n', 'o', 'r', 's', 't']


In [4]:
char_to_idx = {char: idx for idx, char in enumerate(char_list)}
print(char_to_idx)

{' ': 0, ',': 1, '.': 2, ';': 3, 'A': 4, 'C': 5, 'a': 6, 'b': 7, 'c': 8, 'e': 9, 'g': 10, 'h': 11, 'i': 12, 'm': 13, 'n': 14, 'o': 15, 'r': 16, 's': 17, 't': 18}


In [5]:
idx_to_char = np.array(char_list)
print(idx_to_char)

[' ' ',' '.' ';' 'A' 'C' 'a' 'b' 'c' 'e' 'g' 'h' 'i' 'm' 'n' 'o' 'r' 's'
 't']


#### Step 4: Convert text to numerical data

In [6]:
text_as_int = np.array([char_to_idx[char] for char in text])
text_as_int

array([ 4, 14, 14,  6,  1,  0,  9, 13,  7, 16,  6,  8,  9,  0,  8, 11,  6,
       14, 10,  9,  3,  0,  5, 11,  6, 14, 10,  9,  0, 12, 17,  0,  8, 15,
       14, 17, 18,  6, 14, 18,  2])

#### Step 5: Create input-output sequences

In [7]:
seq_length = 5
sequences = []
for i in range(len(text_as_int) - seq_length):
    seq = text_as_int[i:i+seq_length]
    target = text_as_int[i+seq_length]
    sequences.append((seq, target))

sequences[:5]

[(array([ 4, 14, 14,  6,  1]), 0),
 (array([14, 14,  6,  1,  0]), 9),
 (array([14,  6,  1,  0,  9]), 13),
 (array([ 6,  1,  0,  9, 13]), 7),
 (array([ 1,  0,  9, 13,  7]), 16)]

#### Step 6: Separate inputs and targets

In [8]:
X = np.array([seq for seq, target in sequences])
y = np.array([target for seq, target in sequences])

In [9]:
X[:5]

array([[ 4, 14, 14,  6,  1],
       [14, 14,  6,  1,  0],
       [14,  6,  1,  0,  9],
       [ 6,  1,  0,  9, 13],
       [ 1,  0,  9, 13,  7]])

In [10]:
y[:5]

array([ 0,  9, 13,  7, 16])

#### Step 7: One-hot encode the targets

In [11]:
y = to_categorical(y, num_classes=len(char_list))
y[:2]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]])

#### Step 8: Define the model

In [12]:
model = Sequential([
    Embedding(len(char_list), 50, input_length=seq_length),
    LSTM(100, return_sequences=False),
    Dense(len(char_list), activation='softmax')
])

C:\Users\saura\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


#### Step 9: Compile the model

In [13]:
model.compile(optimizer='adam', loss='categorical_crossentropy')

#### Step 10: Train the model

In [14]:
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - loss: 2.9446
Epoch 2/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 2.9376
Epoch 3/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 2.9312
Epoch 4/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9254
Epoch 5/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.9198 
Epoch 6/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.9133
Epoch 7/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.9066 
Epoch 8/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.9001 
Epoch 9/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8930 
Epoch 10/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.8851
Epoch 11/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8748 
Epoch 12/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.8627 
Epoch 13/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8532 
Epoch 14/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 2.8400
Epoch 15/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 2.8244
Epoch 16/500
2/2 ━━

#### Step 11: Generate Text

In [15]:
def generate_text(model, start_string, num_generate=100):
    input_eval = [char_to_idx[char] for char in start_string]
    input_eval = np.array(input_eval).reshape(1, -1)
    
    text_generated = []

    for i in range(num_generate):
        predictions = model.predict(input_eval)
        predicted_id = np.argmax(predictions[0])
        text_generated.append(idx_to_char[predicted_id])
        
        input_eval = np.append(input_eval[:, 1:], predicted_id)
        input_eval = input_eval.reshape(1, -1)

    return start_string + ''.join(text_generated)

In [16]:
print(generate_text(model, start_string="Anna", num_generate=25))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 384ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 368ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
Anna eebacc hnngee  cnstat..e
